[project]
name = "beancount_muonzoo_plugins"
version = "v0.1.0"
description = "Supporting plugins for beancount"
authors = [
    {name = "Alan Hawrylyshen",email = "muonzoo@users.github.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beancount (>=2.3.0, < 4.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 92
# Please note: We use 'ruff format' to autoformat buffers.
# See 'rust-format.el' and .dir-locals.el at the root of the project.

[tool.ruff]
# Assume Python 3.12.
target-version = "py312"

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Same as Black.
line-length = 92

[tool.ruff.lint]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = ["E", "F", "PL", "PD"]
ignore = [
    'E501',
    'E731',
    'E741',
    'PD011',
    'PLR0912',
    'PLR0913',
    'PLR0915',
    'PLR2004',
    'PLR5501',
    'PLW0603',
    'PLW2901',
    'PLW3301',
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
unfixable = []

per-file-ignores = {}

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.poetry.group.dev.dependencies]
ruff = ">=0.11.9"
mkdocs = "^1.6.1"

[tool.poetry.group.test.dependencies]
tox = ">=4.23.2"



[ruff.lint.mccabe]

# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10
